version: "3.3"
services:
  mongodb:
    image: mongo:5.0
    volumes:
      - ~/Projects/mongodb:/data/db
  wa-web:
    image: korenminchev/korenm:1.1
    security_opt:
      - seccomp:chrome_secomp.json
    volumes:
      - ./wwebjs_auth:/app/wwebjs_auth
    command: make run
